# Custom MASUP-specific overrides for VDN

# MapB
algo_args:
  batch_episode: 16
  lr: 0.0005
  rollout_fragment_length: 1
  buffer_size: 500
  target_network_update_freq: 200
  final_epsilon: 0.05
  epsilon_timesteps: 25000000
  optimizer: "adam"
  reward_standardize: True

# # small graphs
# algo_args:
#   batch_episode: 64
#   lr: 0.0005
#   rollout_fragment_length: 1
#   buffer_size: 2000
#   target_network_update_freq: 200
#   final_epsilon: 0.05
#   epsilon_timesteps: 5000000
#   optimizer: "adam"
#   reward_standardize: True